#!/bin/sh
# Author: Quyet Ng.
# Website: quyet.tk
# Created: 03:15PM November 08, 2016 (VN time)
#
# Detect the OS TYPE from a Shell script
platform='unknown'
unamestr=`uname`
if [ "$unamestr" == 'Linux' ]; then
   platform='linux'
elif [ "$unamestr" == 'FreeBSD' ]; then
   platform='freebsd'
fi