#!/bin/sh
# Author: Quyet Ng.
# Website: quyet.tk
# Created: 03:15PM November 08, 2016 (VN time)
#
# Detect the UNIX/LINUX from a Shell script (Support: UNIX/LINUX ; don't Support: WINDOWS, ...)
platform='unknown'
unamestr=`uname`
if [ "$unamestr" == 'Linux' ]; then
   platform='linux'
elif [ "$unamestr" == 'FreeBSD' ]; then
   platform='freebsd'
fi