#!/bin/sh
# Author: Quyet Ng.
# Website: quyet.tk
# Created: 03:15PM November 08, 2016 (VN time)
#
# OS
echo " OS: Debian 8."
echo " This OS does't Support by this Script. Exit."
# Install
#echo "------ Update, Install base ------"
#echo "------ Install OpenJDK ------"
#echo "------ Install Tomcat, OpenSSL ------"
#echo "------ Configuaration Tomcat ------"
#echo "------ Install PostgreSQL ------"
#echo "------ Configuaration PostgreSQL ------"